[[mgr.prepend_keymap]]
on  = "y"
run = [ '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''', "yank" ]

[[mgr.prepend_keymap]]
on  = "<C-t>"
run = "shell --orphan -- ghostty"
desc = "Abrir Ghostty en el CWD"
